# Generated by Django 3.2.3 on 2021-05-23 02:43

from django.db import migrations, models
import profiles.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_pic',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.utilities.get_profile_dp_image_upload_path),
        ),
    ]
