# Generated by Django 3.2.3 on 2021-05-23 02:29

from django.db import migrations, models
import django.db.models.deletion
import profiles.utilities
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('is_deleted', models.BooleanField(default=False)),
                ('otp', models.CharField(max_length=6)),
                ('verifier_tag', models.IntegerField(choices=[(0, 'OTHER'), (1, 'MAIL VERIFICATION'), (2, 'PHONE VERIFICATION'), (3, 'PASSWORD RESET')])),
                ('is_verified', models.BooleanField(default=False)),
                ('notification_type', models.SmallIntegerField(choices=[(0, 'Other'), (1, 'Sms'), (2, 'Email'), (3, 'Push'), (4, 'Call')], default=2)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('is_deleted', models.BooleanField(default=False)),
                ('identity_type', models.CharField(choices=[('UIDAI', 'Uidai'), ('PAN', 'Pan'), ('PASSPORT', 'Passport'), ('DRIVING_LICENSE', 'Driving License'), ('VOTER_ID', 'Voter Id'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('image', models.ImageField(upload_to=profiles.utilities.get_profile_verification_image_upload_path)),
                ('id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('kyc_json', models.JSONField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('is_audited', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
