# Generated by Django 3.2.3 on 2021-09-04 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('proof', '0001_initial'),
        ('tracker', '0001_initial'),
        ('debate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.location'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='proofs',
            field=models.ManyToManyField(blank=True, null=True, to='proof.Proof'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='activity.HashTag'),
        ),
    ]
