# Generated by Django 3.2.3 on 2021-09-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proof', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
