# Generated by Django 3.1.5 on 2021-01-23 19:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proof', '0001_initial'),
        ('activity', '0001_initial'),
        ('tracker', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('question', models.CharField(max_length=450)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.SmallIntegerField(choices=[(0, 'Other'), (1, 'Politics'), (2, 'Sports'), (3, 'Education'), (4, 'Adult'), (5, 'Spiritual'), (6, 'Entertainment'), (7, 'Business'), (8, 'Technology'), (9, 'Nature')], default=0)),
                ('slug', models.CharField(max_length=200)),
                ('for_label', models.CharField(default='For', max_length=100)),
                ('against_label', models.CharField(default='Against', max_length=100)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.location')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('proofs', models.ManyToManyField(to='proof.Proof')),
                ('tags', models.ManyToManyField(to='activity.Tag')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
