# Generated by Django 3.2.3 on 2021-09-03 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proof', '0001_initial'),
        ('activity', '0001_initial'),
        ('tracker', '0001_initial'),
        ('case', '0002_case_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.location'),
        ),
        migrations.AlterField(
            model_name='case',
            name='proofs',
            field=models.ManyToManyField(blank=True, null=True, to='proof.Proof'),
        ),
        migrations.AlterField(
            model_name='case',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='activity.HashTag'),
        ),
    ]
