# Generated by Django 3.2.3 on 2021-10-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.IntegerField(choices=[(0, 'Report'), (1, 'Upvote'), (2, 'Downvote'), (3, 'View')]),
        ),
    ]
